---
apiVersion: v1
kind: ReplicationController
metadata:
  name: app-controller
spec: 
  replicas: 2
  selector:
     app: app
  template:
    metadata:
      labels:
        app: app
    spec:
     containers:
      - name: appcontainer
        image: image/app:V9
        ports:
          - name: app-port
            containerPort: 8080
