---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
    - name: appcontainer
      image: image/app:V9
      ports:
        - name: app-port
          containerPort: 8080
